print("Digite sua quantidade de dias, horas, minutos e segundos e vou calcular o total em segundos")
dias=int(input("Digite a quantidade de dias: "))
horas=int(input("Digite a quantidade de horas: "))
minutos=int(input("Digite a quantidade de minutos: "))
segundos=int(input("Digite a quantidade de segundos: "))
resultado=(dias*86400)+(horas*3600)+(minutos*60)+(segundos)
print("O resultado em segundos é: " , resultado)
